import { useEffect, useState } from "react";
import TableComponent from "../components/TableComponent";
import Badge from "../components/Badge";
import {getAllReports,downloadReport,viewReport} from "../../API/newapi/ReportApi";

const Report = () => {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    getAllReports()
      .then((res) => res.json())
      .then((data) => setReports(data))
      .catch((err) => console.error("Failed to fetch reports", err))
      .finally(() => setLoading(false));
  }, []);

  const onViewReport = (reportId) => {
    viewReport(reportId)
  };

  const onDownloadReport = (reportId) => {
    downloadReport(reportId);
  }

  const columns = [
    {
      key: "index",
      label: "#",
      render: (row)=> row.reportId,
    },
    {
      key: "title",
      label: "Title",
    },
    {
      key: "type",
      label: "Type",
      render: (row) => <Badge label={row.type} />,
    },
    {
      key: "generatedOn",
      label: "Generated On",
      render: (row) => row.generatedOn,
    },
    {
      key: "generatedBy",
      label: "Generated By",
      render: (row) => row.generatedByUserFullname,
    },
    {
      key: "actions",
      label: "Actions",
      render: (row) => (
        <div className="flex gap-2">
          <button className="px-3 py-1 text-xs rounded-lg bg-blue-100 text-blue-700 hover:bg-blue-200" onClick={()=>{onViewReport(row.reportId)}}>
            View
          </button>
          <button className="px-3 py-1 text-xs rounded-lg bg-green-100 text-green-700 hover:bg-green-200" onClick={()=>{onDownloadReport(row.reportId)}}>
            Download
          </button>
        </div>
      ),
    },
  ];

  return (
    <div className="p-6 space-y-6">
      {/* Page Header */}
      <div>
        <h2 className="text-2xl font-semibold text-blue-900">
          Reports
        </h2>
        <p className="text-sm text-blue-500">
          View and manage generated system reports
        </p>
      </div>

      {/* Table */}
      {loading ? (
        <div className="bg-white rounded-xl shadow-md border border-blue-100 p-6 text-center text-blue-400">
          Loading reports...
        </div>
      ) : (
        <TableComponent
          columns={columns}
          data={reports}
        />
      )}
    </div>
  );
};

export default Report;
